# Configuration
# https://jekyllrb.com/docs/configuration/

theme: jekyll-theme-minimal
repository: haezh/U-1F30F
plugins: []
timezone: Europe/Berlin

# SEO
# https://github.com/jekyll/jekyll-seo-tag
title: U-1F30F
description: Earth Travel Memory Marker

# Assets
# https://jekyllrb.com/docs/assets/
sass:
    style: compressed

# Collections
# https://jekyllrb.com/docs/collections/
collections:
- directory

# Exclude directories and/or files from the conversion.
# https://jekyllrb.com/docs/configuration/
exclude:
- CONTRIBUTE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- SETUP.md

# Compress HTML in Jekyll
# http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
