---
# title (required)
title: Title

# geo location (required)
# provide your favored level of detail by number of digits (like 50.107811 vs 50.11)
# you may use services like openstreetmap.org to find out your geo location
latitude: 50.11
longitude: 8.67

# description
# describe yourself, your involvement in the project and the community or whatever is relevant for you.
# should be 300 chars at maximum. no markup or line breaks!
description: "Midnight, there is a sound from the pavement, the moon never loses her memory."

# image or gravatar
# provide image file from current folder (like 'johndoe.jpg') or gravatar url (generated via https://3v4l.org/OXG7H)
# should be square and about 200-300 px size!
image: random.jpg

# links
# one or more links to anything!
# 4 links, tops!
links:
- https://github.com/haezh

---
